name: default_utility
description: A Flutter package providing predefined and customizable Snackbar (toast message) and stateful dialog widgets without needing context.
version: 0.0.4
homepage: https://github.com/shree-krishna-gapi/default_utility

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
# your usual flutter options (assets, etc.)

screenshots:
  - description: 'Basic toast UI'
    path: screenshots/screenshot.png
